groups:
- name: bytecart_alerts
  interval: 30s
  rules:
  - alert: HighCPUUsage
    expr: (100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100)) > 80
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "High CPU usage detected on {{ $labels.instance }}"
      description: "CPU usage exceeded 80% for over 2 minutes." 
  - alert: HighDiskUse
    expr: (1-node_filesystem_free_bytes{"mountpoint"="/etc/resolv.conf"}/node_filesystem_size_bytes{"mountpoint"="/etc/resolv.conf"})*100 > 60
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "High disk use on {{ $labels.instance }}"
      description: "Disk use exceeded 60% for over 2 minutes."

  - alert: InstanceDown
    expr: up==0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} is down"
      description: "Prometheus target is not reachable."